name: "Bug"
description: "๋ฒ๊ทธ๊ฐ ์๊ฒผ์ด์ ๐"
labels: ๋ฒ๊ทธ
body:
  - type: textarea
    attributes:
      label: Describe
      description: |
        ๋ฒ๊ทธ์ ๊ดํ ์ค๋ช์ ๊ฐ๋จํ๊ฒ ์์ฑํด์ฃผ์ธ์.
      placeholder: |
        ๋งค์ฐ ์ฌ๊ฐํ ๋ฒ๊ทธ์์!

  - type: textarea
    attributes:
      label: How
      description: |
        ์ด๋ค API ์์ ์๊ธฐ๋ ๋ฒ๊ทธ์ธ์ง ๊ฐ๋จํ๊ฒ ์ค๋ชํด์ฃผ์ธ์.