name: "Todo"
description: "할일이 있으신가요? 📗"
body:
  - type: textarea
    attributes:
      label: Describe
      description: |
        [개요] 할 일에 관한 설명을 간단하게 작성해주세요.
      placeholder: |
        어떤어떤 API 작성

  - type: textarea
    attributes:
      label: Work
      description: |
        [작업내용] 무슨 작업을 하셨나요?
      placeholder: |
        [ ] 어떤어떤 API 작성했어요
        [ ] 어떤어떤 API 작성을 했습니다.

  - type: textarea
    attributes:
      label: Additional
      description: |
        [추가사항] 추가로 할말이 있으신가요?